remove test file and add error handling to script

diff --git a/bin/build-files b/bin/build-files
--- a/bin/build-files
+++ b/bin/build-files
@@ -2,6 +2,15 @@
 git stash -k
 echo "RUNNING BUILD...... (\°_°)\ ┬─┬"
 yarn build
+
+if [ $? -ne 0 ]; then
+	git stash pop
+	echo "!!!!!!!!!!!!!!!!!!!"
+	echo "BUILD FAILED!!! Try Again...."
+	echo "!!!!!!!!!!!!!!!!!!!"
+	exit 1
+fi
+
 echo "BUILD COMPLETE....."
 git add build
 git stash pop
